apiVersion: v1
kind: Pod
metadata:
  name: load-generator
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["/bin/sh", "-c"]
    args:
    - "while true; do wget -q -O- http://treasurebook-api-service:5000/nodes; done"